name: Build and Deploy Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current version
        id: get_version
        run: |
          if [ ! -f VERSION ]; then echo "0" > VERSION; fi
          echo "Current version: $(cat VERSION)"
      
      - name: Increment version
        id: increment_version
        run: |
          VERSION=$(cat VERSION)
          NEW_VERSION=$((VERSION + 1))
          echo $NEW_VERSION > VERSION
          echo "New version: $NEW_VERSION"
          echo "version=v$NEW_VERSION" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/api-server:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/api-server:${{ env.version }}

      - name: Commit new version
        env:
          GH_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add VERSION
          git commit -m "Increment version to v${{ env.version }}"
          git push https://x-access-token:${{ secrets.DOCKERHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main